name: Node.js CI

# This specifies when the workflow should run.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# This section defines the jobs to run.
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install
    - name: Compile TypeScript
      run: npm run build
    # - name: Run tests
    #   run: npm test



  
